---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apache2-deployment
  namespace: mynamespace
spec:
  selector:
    matchLabels:
      app: apache2
  replicas: 2
  template: 
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: gcr.io/google_containers/hpa-example
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: apache2-deployment-hpa
  namespace: mynamespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache2-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
kind: Service
apiVersion: v1
metadata:
  name: testfrontend2
  namespace: mynamespace
spec:
  selector:
    app: apache2
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer